name: model-fasterml

services:
  model_api:
    image: model_api_image:latest
    container_name: model_api
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    networks:
      - model-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./schemas/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - model_api
    networks:
      - model-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - model-network

networks:
  model-network: 
    name: model-network-1
    driver: bridge