FROM python:3.11-slim

WORKDIR /code

RUN apt-get update && \
    apt-get install -y procps && \
    pip install -U pip && \
    rm /etc/localtime && \
    ln -s /usr/share/zoneinfo/America/Mexico_City /etc/localtime

COPY . /code

RUN	pip install -r requirements.txt && \
    python src/exec.py

EXPOSE 8000

CMD ["fastapi", "run", "src/API.py"]