{
 "title": "Production Overview Updated",
 "tags": [ "templated" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "25s",
 "panels": [
  {
   "title": "CPU Percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "cpu_frequency_mhz", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM Percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ram_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM used bytes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ram_total_bytes", "legendFormat": "__auto" },
    { "expr": "ram_used_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}