[project]
name = "cookiecutter-fasterml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "pyyaml>=6.0.2",
    "sqlalchemy>=2.0.36",
]
